"""Fix patients table columns

Revision ID: 35a6628b186c
Revises: fb2a28f755db
Create Date: 2026-07-15 22:46:00.454807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35a6628b186c'
down_revision: Union[str, Sequence[str], None] = 'fb2a28f755db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.add_column('patients', sa.Column('admission_date', sa.Date(), nullable=False))
    op.alter_column('patients', 'disease',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)
    op.drop_index(op.f('phone'), table_name='patients')
    op.create_foreign_key(None, 'patients', 'doctors', ['doctor_id'], ['id'])
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('address', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('patients', sa.Column('phone', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_index(op.f('phone'), 'patients', ['phone'], unique=True)
    op.alter_column('patients', 'disease',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('patients', 'admission_date')
    op.drop_column('patients', 'doctor_id')
    # ### end Alembic commands ###
